/** structured — generated from Compass Logistics Procurement Synthetic Dataset v1.2 (Bids). Do not import xlsx at runtime. */

export type Bids = {
  eventId: string | null
  supplierId: string | null
  bidStatus: string | null
  annualBidValueEur: string | number | null
  lanesOffered: string | number | null
  capacityScore: string | number | null
  serviceScore: string | number | null
  implementationScore: number | null
  sustainabilityScore: number | null
  vendorHistoryScore: string | number | null
  notes: string | null
}

export const BIDS: Bids[] = [
  {
    eventId: "RFP-2026-001",
    supplierId: "SUP-001",
    bidStatus: "Compliant",
    annualBidValueEur: 2065914.36,
    lanesOffered: 18,
    capacityScore: 100,
    serviceScore: 88,
    implementationScore: 90,
    sustainabilityScore: 78,
    vendorHistoryScore: 90,
    notes: "Incumbent; full network; revised rate card received.",
  },
  {
    eventId: "RFP-2026-001",
    supplierId: "SUP-002",
    bidStatus: "Compliant",
    annualBidValueEur: 2190530.52,
    lanesOffered: 15,
    capacityScore: 82,
    serviceScore: 94,
    implementationScore: 86,
    sustainabilityScore: 83,
    vendorHistoryScore: 90,
    notes: "Higher cost; strongest incumbent performance.",
  },
  {
    eventId: "RFP-2026-001",
    supplierId: "SUP-004",
    bidStatus: "Compliant",
    annualBidValueEur: 1920496.2,
    lanesOffered: 18,
    capacityScore: 76,
    serviceScore: 90,
    implementationScore: 92,
    sustainabilityScore: 91,
    vendorHistoryScore: "No History",
    notes: "Lowest compliant challenger; no internal operating history.",
  },
  {
    eventId: "RFP-2026-001",
    supplierId: "SUP-005",
    bidStatus: "Disqualified",
    annualBidValueEur: 1994320.44,
    lanesOffered: 18,
    capacityScore: 91,
    serviceScore: 84,
    implementationScore: 80,
    sustainabilityScore: 72,
    vendorHistoryScore: "No History",
    notes: "Insurance certificate below mandatory threshold.",
  },
  {
    eventId: "Qualification gates",
    supplierId: null,
    bidStatus: null,
    annualBidValueEur: null,
    lanesOffered: null,
    capacityScore: null,
    serviceScore: null,
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "Qualification gates",
    bidStatus: "Qualification gates",
    annualBidValueEur: "Qualification gates",
    lanesOffered: "Qualification gates",
    capacityScore: "Qualification gates",
    serviceScore: "event_id",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "supplier_id",
    bidStatus: "gate",
    annualBidValueEur: "result",
    lanesOffered: "evidence_source",
    capacityScore: "review_status",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-001",
    bidStatus: "Cargo insurance",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-001",
    bidStatus: "Financial due diligence",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-001",
    bidStatus: "Data integration commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-001",
    bidStatus: "Minimum OTD commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-002",
    bidStatus: "Cargo insurance",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-002",
    bidStatus: "Financial due diligence",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-002",
    bidStatus: "Data integration commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-002",
    bidStatus: "Minimum OTD commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-004",
    bidStatus: "Cargo insurance",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-004",
    bidStatus: "Financial due diligence",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-004",
    bidStatus: "Data integration commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-004",
    bidStatus: "Minimum OTD commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-005",
    bidStatus: "Cargo insurance",
    annualBidValueEur: "Fail",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-005",
    bidStatus: "Financial due diligence",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-005",
    bidStatus: "Data integration commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: "RFP-2026-001",
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  },
  {
    eventId: null,
    supplierId: "SUP-005",
    bidStatus: "Minimum OTD commitment",
    annualBidValueEur: "Pass",
    lanesOffered: "Supplier bid / certificate",
    capacityScore: "Complete",
    serviceScore: null,
    implementationScore: null,
    sustainabilityScore: null,
    vendorHistoryScore: null,
    notes: null,
  }
]
