/** structured — generated from Compass Logistics Procurement Synthetic Dataset v1.2 (Incidents). Do not import xlsx at runtime. */

export type Incidents = {
  incidentId: string | null
  shipmentId: string | null
  supplierId: string | null
  laneId: string | null
  incidentDate: string | null
  incidentType: string | null
  severity: string | null
  description: string | null
  status: string | null
  correctiveActionId: string | null
}

export const INCIDENTS: Incidents[] = [
  {
    incidentId: "INC-0001",
    shipmentId: "SHP-00058",
    supplierId: "SUP-001",
    laneId: "LN-005",
    incidentDate: "2025-10-05",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0002",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00136",
    supplierId: "SUP-003",
    laneId: "LN-012",
    incidentDate: "2025-10-18",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0003",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00188",
    supplierId: "SUP-001",
    laneId: "LN-017",
    incidentDate: "2025-10-18",
    incidentType: "Damage claim",
    severity: "High",
    description: "Packaging damage reported at receipt.",
    status: "Closed",
    correctiveActionId: "INC-0004",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00200",
    supplierId: "SUP-003",
    laneId: "LN-018",
    incidentDate: "2025-10-17",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0005",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00235",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2025-11-11",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0006",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00237",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2025-11-14",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0007",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00259",
    supplierId: "SUP-001",
    laneId: "LN-004",
    incidentDate: "2025-11-23",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0008",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00266",
    supplierId: "SUP-001",
    laneId: "LN-005",
    incidentDate: "2025-11-12",
    incidentType: "Damage claim",
    severity: "High",
    description: "Packaging damage reported at receipt.",
    status: "Closed",
    correctiveActionId: "INC-0009",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00309",
    supplierId: "SUP-003",
    laneId: "LN-009",
    incidentDate: "2025-11-15",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0010",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00314",
    supplierId: "SUP-001",
    laneId: "LN-010",
    incidentDate: "2025-11-04",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0011",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00330",
    supplierId: "SUP-002",
    laneId: "LN-011",
    incidentDate: "2025-11-17",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0012",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00354",
    supplierId: "SUP-002",
    laneId: "LN-014",
    incidentDate: "2025-11-16",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0013",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00371",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2025-11-23",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0014",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00374",
    supplierId: "SUP-001",
    laneId: "LN-016",
    incidentDate: "2025-11-06",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0015",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00465",
    supplierId: "SUP-001",
    laneId: "LN-005",
    incidentDate: "2025-12-04",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0016",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00522",
    supplierId: "SUP-001",
    laneId: "LN-010",
    incidentDate: "2025-12-14",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0017",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00545",
    supplierId: "SUP-003",
    laneId: "LN-012",
    incidentDate: "2025-12-21",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0018",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00566",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2025-12-10",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0019",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00605",
    supplierId: "SUP-003",
    laneId: "LN-018",
    incidentDate: "2025-12-11",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0020",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00642",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2026-01-09",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0021",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00683",
    supplierId: "SUP-003",
    laneId: "LN-006",
    incidentDate: "2026-01-05",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0022",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00690",
    supplierId: "SUP-003",
    laneId: "LN-006",
    incidentDate: "2026-01-19",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0023",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00720",
    supplierId: "SUP-003",
    laneId: "LN-009",
    incidentDate: "2026-01-22",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0024",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00774",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-01-16",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0025",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00782",
    supplierId: "SUP-001",
    laneId: "LN-016",
    incidentDate: "2026-01-06",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0026",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00821",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-02-10",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0027",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00844",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2026-02-06",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0028",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00901",
    supplierId: "SUP-001",
    laneId: "LN-007",
    incidentDate: "2026-02-10",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0029",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00937",
    supplierId: "SUP-002",
    laneId: "LN-011",
    incidentDate: "2026-02-07",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0030",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00974",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-02-10",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0031",
  },
  {
    incidentId: null,
    shipmentId: "SHP-00979",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-02-17",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0032",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01016",
    supplierId: "SUP-003",
    laneId: "LN-018",
    incidentDate: "2026-02-17",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0033",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01032",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-03-22",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0034",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01040",
    supplierId: "SUP-001",
    laneId: "LN-002",
    incidentDate: "2026-03-14",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0035",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01120",
    supplierId: "SUP-003",
    laneId: "LN-009",
    incidentDate: "2026-03-04",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0036",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01148",
    supplierId: "SUP-002",
    laneId: "LN-011",
    incidentDate: "2026-03-21",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0037",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01189",
    supplierId: "SUP-001",
    laneId: "LN-016",
    incidentDate: "2026-03-04",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0038",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01271",
    supplierId: "SUP-001",
    laneId: "LN-004",
    incidentDate: "2026-04-11",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0039",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01298",
    supplierId: "SUP-003",
    laneId: "LN-006",
    incidentDate: "2026-04-11",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0040",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01304",
    supplierId: "SUP-003",
    laneId: "LN-006",
    incidentDate: "2026-04-23",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0041",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01310",
    supplierId: "SUP-001",
    laneId: "LN-007",
    incidentDate: "2026-04-13",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0042",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01362",
    supplierId: "SUP-003",
    laneId: "LN-012",
    incidentDate: "2026-04-24",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0043",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01453",
    supplierId: "SUP-001",
    laneId: "LN-002",
    incidentDate: "2026-05-24",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0044",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01471",
    supplierId: "SUP-001",
    laneId: "LN-004",
    incidentDate: "2026-05-05",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0045",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01497",
    supplierId: "SUP-001",
    laneId: "LN-005",
    incidentDate: "2026-05-25",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0046",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01508",
    supplierId: "SUP-003",
    laneId: "LN-006",
    incidentDate: "2026-05-23",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0047",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01538",
    supplierId: "SUP-001",
    laneId: "LN-010",
    incidentDate: "2026-05-04",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0048",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01578",
    supplierId: "SUP-002",
    laneId: "LN-014",
    incidentDate: "2026-05-16",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0049",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01589",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-05-14",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0050",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01732",
    supplierId: "SUP-003",
    laneId: "LN-009",
    incidentDate: "2026-06-04",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0051",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01766",
    supplierId: "SUP-003",
    laneId: "LN-012",
    incidentDate: "2026-06-12",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0052",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01786",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-06-04",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0053",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01825",
    supplierId: "SUP-003",
    laneId: "LN-018",
    incidentDate: "2026-06-04",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0054",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01837",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-07-04",
    incidentType: "Damage claim",
    severity: "High",
    description: "Packaging damage reported at receipt.",
    status: "Closed",
    correctiveActionId: "INC-0055",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01838",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-07-05",
    incidentType: "Damage claim",
    severity: "High",
    description: "Packaging damage reported at receipt.",
    status: "Closed",
    correctiveActionId: "INC-0056",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01843",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-07-13",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0057",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01849",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-07-23",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0058",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01866",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2026-07-09",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0059",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01889",
    supplierId: "SUP-001",
    laneId: "LN-004",
    incidentDate: "2026-07-20",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0060",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01962",
    supplierId: "SUP-002",
    laneId: "LN-011",
    incidentDate: "2026-07-17",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0061",
  },
  {
    incidentId: null,
    shipmentId: "SHP-01972",
    supplierId: "SUP-003",
    laneId: "LN-012",
    incidentDate: "2026-07-18",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0062",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02031",
    supplierId: "SUP-003",
    laneId: "LN-018",
    incidentDate: "2026-07-07",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Closed",
    correctiveActionId: "INC-0063",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02047",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-08-13",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0064",
    shipmentId: "SHP-02076",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2026-08-18",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "INC-0065",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02093",
    supplierId: "SUP-001",
    laneId: "LN-004",
    incidentDate: "2026-08-20",
    incidentType: "Damage claim",
    severity: "High",
    description: "Packaging damage reported at receipt.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0066",
    shipmentId: "SHP-02100",
    supplierId: "SUP-001",
    laneId: "LN-005",
    incidentDate: "2026-08-09",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0067",
    shipmentId: "SHP-02128",
    supplierId: "SUP-001",
    laneId: "LN-007",
    incidentDate: "2026-08-17",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Open",
    correctiveActionId: "INC-0068",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02195",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-08-05",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0069",
    shipmentId: "SHP-02199",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-08-11",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0070",
    shipmentId: "SHP-02247",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-09-07",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0071",
    shipmentId: "SHP-02253",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-09-17",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0072",
    shipmentId: "SHP-02254",
    supplierId: "SUP-001",
    laneId: "LN-001",
    incidentDate: "2026-09-18",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0073",
    shipmentId: "SHP-02276",
    supplierId: "SUP-003",
    laneId: "LN-003",
    incidentDate: "2026-09-12",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Open",
    correctiveActionId: "INC-0074",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02327",
    supplierId: "SUP-001",
    laneId: "LN-007",
    incidentDate: "2026-09-06",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "INC-0075",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02396",
    supplierId: "SUP-002",
    laneId: "LN-014",
    incidentDate: "2026-09-21",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "INC-0076",
  },
  {
    incidentId: null,
    shipmentId: "SHP-02399",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-09-05",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 8 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0077",
    shipmentId: "SHP-02400",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-09-07",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 24 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0078",
    shipmentId: "SHP-02405",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-09-14",
    incidentType: "Late delivery",
    severity: "High",
    description: "Delivery completed 36 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  },
  {
    incidentId: "INC-0079",
    shipmentId: "SHP-02411",
    supplierId: "SUP-001",
    laneId: "LN-015",
    incidentDate: "2026-09-23",
    incidentType: "Late delivery",
    severity: "Medium",
    description: "Delivery completed 12 hours after commitment.",
    status: "Open",
    correctiveActionId: "CAP-001",
  }
]
