/** structured — generated from Compass Logistics Procurement Synthetic Dataset v1.2 (Lanes). Do not import xlsx at runtime. */

export type Lanes = {
  laneId: string | null
  originCity: string | null
  originCountry: string | null
  destinationCity: string | null
  destinationCountry: string | null
  distanceKm: number | null
  forecastAnnualShipments: number | null
  targetTransitHours: number | null
  temperatureControl: string | null
  equipment: string | null
  currency: string | null
}

export const LANES: Lanes[] = [
  {
    laneId: "LN-001",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Paris",
    destinationCountry: "FR",
    distanceKm: 580,
    forecastAnnualShipments: 168,
    targetTransitHours: 6,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-002",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Lyon",
    destinationCountry: "FR",
    distanceKm: 700,
    forecastAnnualShipments: 132,
    targetTransitHours: 8,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-003",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Rotterdam",
    destinationCountry: "NL",
    distanceKm: 445,
    forecastAnnualShipments: 192,
    targetTransitHours: 6,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-004",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Brussels",
    destinationCountry: "BE",
    distanceKm: 405,
    forecastAnnualShipments: 180,
    targetTransitHours: 6,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-005",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Milan",
    destinationCountry: "IT",
    distanceKm: 665,
    forecastAnnualShipments: 156,
    targetTransitHours: 10,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-006",
    originCity: "Frankfurt",
    originCountry: "DE",
    destinationCity: "Vienna",
    destinationCountry: "AT",
    distanceKm: 600,
    forecastAnnualShipments: 144,
    targetTransitHours: 8,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-007",
    originCity: "Hamburg",
    originCountry: "DE",
    destinationCity: "Copenhagen",
    destinationCountry: "DK",
    distanceKm: 335,
    forecastAnnualShipments: 120,
    targetTransitHours: 5,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-008",
    originCity: "Hamburg",
    originCountry: "DE",
    destinationCity: "Stockholm",
    destinationCountry: "SE",
    distanceKm: 1015,
    forecastAnnualShipments: 96,
    targetTransitHours: 16,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-009",
    originCity: "Hamburg",
    originCountry: "DE",
    destinationCity: "Warsaw",
    destinationCountry: "PL",
    distanceKm: 860,
    forecastAnnualShipments: 120,
    targetTransitHours: 12,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-010",
    originCity: "Hamburg",
    originCountry: "DE",
    destinationCity: "Prague",
    destinationCountry: "CZ",
    distanceKm: 650,
    forecastAnnualShipments: 108,
    targetTransitHours: 10,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-011",
    originCity: "Cologne",
    originCountry: "DE",
    destinationCity: "London",
    destinationCountry: "GB",
    distanceKm: 600,
    forecastAnnualShipments: 144,
    targetTransitHours: 12,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-012",
    originCity: "Cologne",
    originCountry: "DE",
    destinationCity: "Birmingham",
    destinationCountry: "GB",
    distanceKm: 700,
    forecastAnnualShipments: 96,
    targetTransitHours: 14,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-013",
    originCity: "Cologne",
    originCountry: "DE",
    destinationCity: "Madrid",
    destinationCountry: "ES",
    distanceKm: 1670,
    forecastAnnualShipments: 72,
    targetTransitHours: 24,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-014",
    originCity: "Cologne",
    originCountry: "DE",
    destinationCity: "Zurich",
    destinationCountry: "CH",
    distanceKm: 575,
    forecastAnnualShipments: 108,
    targetTransitHours: 9,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-015",
    originCity: "Munich",
    originCountry: "DE",
    destinationCity: "Milan",
    destinationCountry: "IT",
    distanceKm: 495,
    forecastAnnualShipments: 180,
    targetTransitHours: 7,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-016",
    originCity: "Munich",
    originCountry: "DE",
    destinationCity: "Bologna",
    destinationCountry: "IT",
    distanceKm: 565,
    forecastAnnualShipments: 120,
    targetTransitHours: 8,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-017",
    originCity: "Munich",
    originCountry: "DE",
    destinationCity: "Vienna",
    destinationCountry: "AT",
    distanceKm: 435,
    forecastAnnualShipments: 168,
    targetTransitHours: 6,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  },
  {
    laneId: "LN-018",
    originCity: "Munich",
    originCountry: "DE",
    destinationCity: "Prague",
    destinationCountry: "CZ",
    distanceKm: 380,
    forecastAnnualShipments: 144,
    targetTransitHours: 6,
    temperatureControl: "No",
    equipment: "Curtainsider / box trailer",
    currency: "EUR",
  }
]
