/** structured — generated from Compass Logistics Procurement Synthetic Dataset v1.2 (Sourcing). Do not import xlsx at runtime. */

export type Sourcing = {
  eventId: string | null
  eventTitle: string | null
  eventType: string | null
  category: string | null
  issueDate: string | null
  questionDeadline: string | null
  bidDeadline: string | number | null
  awardTarget: string | null
  serviceStart: string | null
  contractTermMonths: string | number | null
  lanes: string | number | null
  forecastShipments: string | number | null
  estimatedValueEur: string | number | null
  status: string | null
  owner: string | null
  workingLanguage: string | null
}

export const SOURCING: Sourcing[] = [
  {
    eventId: "RFP-2026-001",
    eventTitle: "European Road Freight Services 2027",
    eventType: "RFP",
    category: "Logistics services - road freight",
    issueDate: "2026-09-28",
    questionDeadline: "2026-10-09",
    bidDeadline: "2026-10-23",
    awardTarget: "2026-11-20",
    serviceStart: "2027-01-01",
    contractTermMonths: 24,
    lanes: 18,
    forecastShipments: 2448,
    estimatedValueEur: 5650000,
    status: "Draft",
    owner: "Category Manager, Logistics",
    workingLanguage: "British English and German",
  },
  {
    eventId: "Expected extracted requirement register",
    eventTitle: null,
    eventType: null,
    category: null,
    issueDate: null,
    questionDeadline: null,
    bidDeadline: null,
    awardTarget: null,
    serviceStart: null,
    contractTermMonths: null,
    lanes: null,
    forecastShipments: null,
    estimatedValueEur: null,
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "Expected extracted requirement register",
    eventType: "Expected extracted requirement register",
    category: "Expected extracted requirement register",
    issueDate: "Expected extracted requirement register",
    questionDeadline: "Expected extracted requirement register",
    bidDeadline: "Expected extracted requirement register",
    awardTarget: "Expected extracted requirement register",
    serviceStart: "Expected extracted requirement register",
    contractTermMonths: "Expected extracted requirement register",
    lanes: "Expected extracted requirement register",
    forecastShipments: "Expected extracted requirement register",
    estimatedValueEur: "requirement_id",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "event_id",
    eventType: "category",
    category: "requirement",
    issueDate: "mandatory",
    questionDeadline: "evaluation_area",
    bidDeadline: "weight_pct",
    awardTarget: "source_document_ids",
    serviceStart: "source_sections",
    contractTermMonths: "extraction_status",
    lanes: "confidence",
    forecastShipments: "user_decision",
    estimatedValueEur: "REQ-001",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Service",
    category: "Provide FTL and LTL road-freight capacity for all offered lanes.",
    issueDate: "Yes",
    questionDeadline: "Service capability",
    bidDeadline: 15,
    awardTarget: "SRC-001",
    serviceStart: "Service scope",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-002",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Performance",
    category: "Commit to on-time delivery of at least 98.0%.",
    issueDate: "Yes",
    questionDeadline: "Service quality",
    bidDeadline: 15,
    awardTarget: "SRC-001; SRC-002; SRC-009",
    serviceStart: "Required service measures / Performance thresholds",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-003",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Performance",
    category: "Commit to a shipment acceptance rate of at least 97.0%.",
    issueDate: "Yes",
    questionDeadline: "Capacity reliability",
    bidDeadline: 10,
    awardTarget: "SRC-001; SRC-002; SRC-009",
    serviceStart: "Required service measures / Performance thresholds",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-004",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Compliance",
    category: "Maintain cargo liability insurance of at least EUR 5 million.",
    issueDate: "Yes",
    questionDeadline: "Qualification gate",
    bidDeadline: 0,
    awardTarget: "SRC-004; SRC-008",
    serviceStart: "Liability and insurance / Mandatory evidence",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-005",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Technology",
    category: "Provide milestone status data by API, EDI or agreed daily file.",
    issueDate: "Yes",
    questionDeadline: "Implementation",
    bidDeadline: 10,
    awardTarget: "SRC-001; SRC-006",
    serviceStart: "Shipment visibility / Connectivity",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-006",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Commercial",
    category: "Submit fixed lane rates in EUR, with fuel surcharge formula and accessorial schedule.",
    issueDate: "Yes",
    questionDeadline: "Commercial",
    bidDeadline: 35,
    awardTarget: "SRC-005",
    serviceStart: "Lane pricing / Fuel surcharge / Accessorials",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-007",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Sustainability",
    category: "Report CO2e by shipment and describe reduction initiatives.",
    issueDate: "No",
    questionDeadline: "Sustainability",
    bidDeadline: 5,
    awardTarget: "SRC-007",
    serviceStart: "Emissions reporting / Improvement plan",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: "REQ-008",
    status: null,
    owner: null,
    workingLanguage: null,
  },
  {
    eventId: null,
    eventTitle: "RFP-2026-001",
    eventType: "Vendor history",
    category: "Incumbent operating performance may contribute to evaluation; new suppliers remain marked No History.",
    issueDate: "No",
    questionDeadline: "Vendor history",
    bidDeadline: 10,
    awardTarget: "SRC-008; SRC-010",
    serviceStart: "New suppliers / Sourcing implication",
    contractTermMonths: "Approved for expected output",
    lanes: "High",
    forecastShipments: "Accept",
    estimatedValueEur: null,
    status: null,
    owner: null,
    workingLanguage: null,
  }
]
