/** expected_generated_outputs — generated from Compass Logistics Procurement Synthetic Dataset v1.2 (Emails). Do not import xlsx at runtime. */

export type Emails = {
  emailId: string | null
  fileName: string | null
  date: string | null
  from: string | null
  to: string | null
  subject: string | null
  language: string | null
  expectedClassification: string | null
  eventId: string | null
  supplierId: string | null
  attachments: string | null
}

export const EMAILS: Emails[] = [
  {
    emailId: "EML-001",
    fileName: "001_rfp_invitation_en.eml",
    date: "Tue, 29 Sep 2026 09:00:00 +0000",
    from: "sourcing@compass-demo.example",
    to: "daniel.foster@northbridge.example",
    subject: "Invitation: European Road Freight Services 2027",
    language: "EN",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "RFP_EN.docx; Lane_Rate_Template.csv",
    attachments: null,
  },
  {
    emailId: "EML-002",
    fileName: "002_rfp_einladung_de.eml",
    date: "Wed, 30 Sep 2026 09:00:00 +0000",
    from: "sourcing@compass-demo.example",
    to: "lena.vogt@rheinroute.example",
    subject: "Einladung: Europaeische Strassentransporte 2027",
    language: "DE",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "RFP_DE.docx; Lane_Rate_Template.csv",
    attachments: null,
  },
  {
    emailId: "EML-003",
    fileName: "003_supplier_acknowledgement.eml",
    date: "Thu, 01 Oct 2026 09:00:00 +0000",
    from: "sofia.keller@alpinelink.example",
    to: "sourcing@compass-demo.example",
    subject: "RE: European Road Freight Services 2027",
    language: "EN",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "SUP-004",
    attachments: "EML-004",
  },
  {
    emailId: null,
    fileName: "004_fuel_surcharge_question.eml",
    date: "Fri, 02 Oct 2026 09:00:00 +0000",
    from: "daniel.foster@northbridge.example",
    to: "sourcing@compass-demo.example",
    subject: "Clarification 02 - fuel surcharge baseline",
    language: "EN",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "SUP-002",
    attachments: "EML-005",
  },
  {
    emailId: null,
    fileName: "005_interne_rueckfrage.eml",
    date: "Sat, 03 Oct 2026 09:00:00 +0000",
    from: "procurement.manager@compass-demo.example",
    to: "sourcing@compass-demo.example",
    subject: "AW: Fracht-Ausschreibung - Volumenbasis",
    language: "DE",
    expectedClassification: "Ambiguous",
    eventId: "RFP-2026-001",
    supplierId: "EML-006",
    attachments: null,
  },
  {
    emailId: null,
    fileName: "006_industry_newsletter.eml",
    date: "Sun, 04 Oct 2026 09:00:00 +0000",
    from: "newsletter@freight-week.example",
    to: "sourcing@compass-demo.example",
    subject: "European freight market weekly update",
    language: "EN",
    expectedClassification: "Irrelevant",
    eventId: "EML-007",
    supplierId: null,
    attachments: null,
  },
  {
    emailId: null,
    fileName: "007_bid_submission_alpinelink.eml",
    date: "Mon, 05 Oct 2026 09:00:00 +0000",
    from: "sofia.keller@alpinelink.example",
    to: "sourcing@compass-demo.example",
    subject: "Bid submission - AlpineLink - RFP-2026-001",
    language: "EN",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "SUP-004",
    attachments: "AlpineLink_Bid_Response.docx; AlpineLink_Rate_Card.csv",
  },
  {
    emailId: "EML-008",
    fileName: "008_revised_rate_card.eml",
    date: "Tue, 06 Oct 2026 09:00:00 +0000",
    from: "lena.vogt@rheinroute.example",
    to: "sourcing@compass-demo.example",
    subject: "Korrigierte Preisliste - RFP-2026-001",
    language: "DE",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "SUP-001",
    attachments: "RheinRoute_Rate_Card_v2.csv",
  },
  {
    emailId: "EML-009",
    fileName: "009_insurance_exception.eml",
    date: "Wed, 07 Oct 2026 09:00:00 +0000",
    from: "marco.bianchi@veloce.example",
    to: "sourcing@compass-demo.example",
    subject: "Insurance certificate update",
    language: "EN",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "SUP-005",
    attachments: "Veloce_Insurance_Certificate.txt",
  },
  {
    emailId: "EML-010",
    fileName: "010_delivery_alert_de.eml",
    date: "Thu, 08 Oct 2026 09:00:00 +0000",
    from: "operations@compass-demo.example",
    to: "supplier.management@compass-demo.example",
    subject: "Leistungsabweichung RheinRoute - August",
    language: "DE",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "EML-011",
    attachments: null,
  },
  {
    emailId: null,
    fileName: "011_corrective_action_outgoing.eml",
    date: "Fri, 09 Oct 2026 09:00:00 +0000",
    from: "supplier.management@compass-demo.example",
    to: "lena.vogt@rheinroute.example",
    subject: "Aufforderung zum Massnahmenplan - Lieferperformance",
    language: "DE",
    expectedClassification: "Relevant",
    eventId: "RFP-2026-001",
    supplierId: "Corrective_Action_Request_DE.docx",
    attachments: null,
  },
  {
    emailId: "EML-012",
    fileName: "012_automatic_reply.eml",
    date: "Sat, 10 Oct 2026 09:00:00 +0000",
    from: "no-reply@rheinroute.example",
    to: "supplier.management@compass-demo.example",
    subject: "Automatische Antwort / Automatic reply",
    language: "DE",
    expectedClassification: "Irrelevant",
    eventId: null,
    supplierId: null,
    attachments: null,
  }
]
